
import React, { useState } from 'react';
import { geminiService } from '../services/geminiService';
import { GeneratedImage } from '../types';

const ImageGenerator: React.FC = () => {
  const [prompt, setPrompt] = useState('');
  const [aspectRatio, setAspectRatio] = useState<"1:1" | "16:9" | "9:16">("1:1");
  const [images, setImages] = useState<GeneratedImage[]>([]);
  const [isLoading, setIsLoading] = useState(false);

  const handleGenerate = async () => {
    if (!prompt.trim() || isLoading) return;

    setIsLoading(true);
    try {
      const imageUrl = await geminiService.generateImage(prompt, aspectRatio);
      const newImage: GeneratedImage = {
        id: Date.now().toString(),
        url: imageUrl,
        prompt: prompt,
        timestamp: new Date()
      };
      setImages(prev => [newImage, ...prev]);
    } catch (error) {
      console.error('Image gen error:', error);
      alert('Failed to generate image. Please try again.');
    } finally {
      setIsLoading(false);
    }
  };

  const ratios = [
    { label: '1:1 Square', value: '1:1' as const },
    { label: '16:9 Landscape', value: '16:9' as const },
    { label: '9:16 Portrait', value: '9:16' as const },
  ];

  return (
    <div className="space-y-8 h-full">
      <div className="bg-gray-900/50 p-6 rounded-3xl border border-gray-800 backdrop-blur-sm">
        <div className="space-y-4">
          <label className="block text-sm font-medium text-gray-400">Describe what you want to create</label>
          <textarea
            value={prompt}
            onChange={(e) => setPrompt(e.target.value)}
            placeholder="A surreal landscape with floating islands and neon waterfalls..."
            className="w-full bg-gray-950 text-white border border-gray-800 rounded-2xl p-4 focus:ring-1 focus:ring-indigo-500/50 focus:border-indigo-500/50 outline-none h-32 resize-none transition-all"
          />
          
          <div className="flex flex-wrap items-center gap-4">
            <div className="flex bg-gray-950 p-1 rounded-xl border border-gray-800">
              {ratios.map((r) => (
                <button
                  key={r.value}
                  onClick={() => setAspectRatio(r.value)}
                  className={`px-4 py-2 rounded-lg text-xs font-semibold transition-all ${
                    aspectRatio === r.value 
                      ? 'bg-indigo-600 text-white shadow-md' 
                      : 'text-gray-500 hover:text-white'
                  }`}
                >
                  {r.label}
                </button>
              ))}
            </div>
            
            <button
              onClick={handleGenerate}
              disabled={isLoading || !prompt.trim()}
              className="flex-1 min-w-[140px] px-8 py-3 bg-indigo-600 hover:bg-indigo-500 disabled:bg-gray-800 disabled:text-gray-600 text-white font-bold rounded-xl transition-all flex items-center justify-center gap-2 active:scale-95 shadow-lg shadow-indigo-600/10"
            >
              {isLoading ? (
                <>
                  <svg className="animate-spin h-4 w-4 text-white" viewBox="0 0 24 24"><circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" fill="none" /><path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" /></svg>
                  Imagining...
                </>
              ) : (
                'Generate Image'
              )}
            </button>
          </div>
        </div>
      </div>

      {images.length > 0 ? (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 animate-in fade-in slide-in-from-bottom-4 duration-500">
          {images.map((img) => (
            <div key={img.id} className="group relative bg-gray-900 border border-gray-800 rounded-2xl overflow-hidden hover:border-indigo-500/30 transition-all">
              <img src={img.url} alt={img.prompt} className="w-full h-auto object-cover transition-transform duration-500 group-hover:scale-105" />
              <div className="p-4 bg-gray-900/95 backdrop-blur-sm border-t border-gray-800">
                <p className="text-xs text-gray-400 line-clamp-2 italic">"{img.prompt}"</p>
                <div className="mt-3 flex items-center justify-between">
                  <span className="text-[10px] text-gray-600 uppercase tracking-widest font-bold">Generated by Visionary</span>
                  <a 
                    href={img.url} 
                    download={`nexus-ai-${img.id}.png`}
                    className="p-1.5 text-gray-400 hover:text-white hover:bg-gray-800 rounded-lg transition-colors"
                  >
                    <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" /></svg>
                  </a>
                </div>
              </div>
            </div>
          ))}
        </div>
      ) : !isLoading && (
        <div className="flex flex-col items-center justify-center py-20 text-gray-600 space-y-4">
          <div className="w-20 h-20 bg-gray-900 rounded-full flex items-center justify-center border border-gray-800">
            <svg className="w-8 h-8 opacity-20" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" /></svg>
          </div>
          <p className="text-sm font-medium">Your masterpieces will appear here</p>
        </div>
      )}
    </div>
  );
};

export default ImageGenerator;
